"""Add ab_group to users

Revision ID: 345c0782c322
Revises: c828e074e32c
Create Date: 2026-06-29 20:04:08.036189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345c0782c322'
down_revision = 'c828e074e32c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ab_group', sa.String(length=20), server_default='control', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ab_group')
    # ### end Alembic commands ###